### ISSUE TITLE
Issue on experimental results in paper

### ISSUE THREAD

**Issue by huanmx** [amazon-science/path-consistency#6]
Hi,
Thanks for your wonderful work!
Based on the code you provided, it seems that the test set was involved in the training process. Could you please confirm if the experimental results on mot17 reported in the paper were also generated with the test set involved in the training?

**Comment by ZijiaLewisLu** [comment]
Hi, 
Thanks for your interest in our work.
For the purpose of consistent comparison, we follow the data split from prior work, [UNS](https://github.com/favyen/uns20),  that uses all data for training. Since our method is unsupervised, the tracking labels are never used at training.
